In [4]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Creation of  the dataset
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

# Build MLP
model = Sequential([
    Dense(4, activation='relu', input_shape=(2,)),  # Hidden layer with 4 neurons and ReLU activation
    Dense(1, activation='sigmoid')                  # Output layer with sigmoid activation
])

# Compilation of the model
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Training the model
history = model.fit(X, y,
                    epochs=5000,  # Increased epochs for better learning
                    batch_size=1,
                    verbose=0)

# Evaluation the model
test_input = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
predictions = model.predict(test_input)
print("XOR predictions:")
print(np.round(predictions.flatten()))  # Convertion to binary outputs

# Checking accuracy
correct_predictions = np.sum(np.round(predictions.flatten()) == np.concatenate([y.flatten()]))
print(f"Accuracy: {correct_predictions/4*100}%")


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
XOR predictions:
[0. 1. 1. 0.]
Accuracy: 100.0%


In [2]:
import torch
import torch.nn as nn
import torch.optim as optim

# Creation of the dataset
X = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)
y = torch.tensor([[0], [1], [1], [0]], dtype=torch.float32)

# Defining the MLP model
class XORNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(2, 4)  # Hidden layer with 4 neurons
        self.fc2 = nn.Linear(4, 1)
        self.relu = nn.ReLU()
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.sigmoid(self.fc2(x))
        return x

# Initializing model, loss function, and optimizer
model = XORNet()
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Training the model
num_epochs = 5000
for epoch in range(num_epochs):
    model.train()
    optimizer.zero_grad()
    outputs = model(X)
    loss = criterion(outputs, y)
    loss.backward()
    optimizer.step()

    if (epoch + 1) % 1000 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.6f}')

# Evaluation the model
model.eval()
with torch.no_grad():
    test_input = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)
    outputs = model(test_input)
    predictions = torch.round(outputs.flatten())
    print("XOR predictions:")
    print(predictions.numpy())


Epoch [1000/5000], Loss: 0.002712
Epoch [2000/5000], Loss: 0.000667
Epoch [3000/5000], Loss: 0.000270
Epoch [4000/5000], Loss: 0.000131
Epoch [5000/5000], Loss: 0.000069
XOR predictions:
[0. 1. 1. 0.]


In [5]:
import tensorflow as tf
import numpy as np # Import numpy
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Create the dataset
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

# Build the MLP using Keras (TF 2.x style)
model = Sequential([
    Dense(4, activation='relu', input_shape=(2,)),  # Hidden layer with 4 neurons and ReLU activation
    Dense(1, activation='sigmoid')                  # Output layer with sigmoid activation
])

# Compilation the model
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Training the model
history = model.fit(X, y,
                    epochs=5000,  # Increased epochs for better learning
                    batch_size=1,
                    verbose=0)

# Evaluation the model
test_input = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
predictions = model.predict(test_input)
print("XOR predictions:")
print(np.round(predictions.flatten()))  # Convertion to binary outputs

# Checking accuracy
correct_predictions = np.sum(np.round(predictions.flatten()) == np.concatenate([y.flatten()]))
print(f"Accuracy: {correct_predictions/4*100}%")

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
XOR predictions:
[0. 1. 1. 0.]
Accuracy: 100.0%
